Feature/accessibility table
Problematy/goodmap-frontend pull request #54
Opened 2024-10-07 15:57 UTC by x-Milosz

Adds accessibility table.

see: https://github.com/Problematy/goodmap/issues/107.

I needed code from https://github.com/Problematy/goodmap-frontend/pull/51, so code from there is included here too.

2024-10-09 11:50 UTC, raven-wing requested changes
Tests for table would be much apreciated.

2024-10-22 17:51 UTC, raven-wing commented
it's probably connected with @Dawid-Sroka changes with #53, but it looks like this now:
![2024-10-22-194959_790x182_scrot](https://github.com/user-attachments/assets/c4a5a7a1-8945-4a59-a62e-62f90ee06a52)

2024-10-30 15:17 UTC, x-Milosz commented
@raven-wing Ajusted to new data format

2024-11-13 12:37 UTC, Dawid-Sroka commented on src/services/http/httpService.js
> +    getLocationsWithLatLon: async (lat, lon, allCheckboxes) => {
I think this function should be modified.
Now, when no filters are checked, the accessability table shows no points:
<img src=https://github.com/user-attachments/assets/21a2de89-f22e-4a4a-bdd3-d81bb910f0b7 width=70% height=70%>
This is not consistent and not what we want. When no filters are checked, the closest points should be chosen from all the points.

2024-11-13 12:44 UTC, Dawid-Sroka commented on src/services/http/httpService.js
> +    getLocationsWithLatLon: async (lat, lon, allCheckboxes) => {
Another thing. When I have the table open and I check e.g. "pedestrians", the location "Zwierzyniecka" appears in the table. But when I uncheck it, the location still remains in the table:
<img src=https://github.com/user-attachments/assets/9e316878-9f82-4752-aedc-abccecf86f08 width=70% height=70%>

2024-11-13 12:51 UTC, Dawid-Sroka commented on src/services/http/httpService.js
> +    getLocationsWithLatLon: async (lat, lon, allCheckboxes) => {
Also - "Grunwaldzki" location should also be displayed in the scenario above. There is something not right with this location. When I have the table open and I try to check a filter, that would return **only** this "Grunwaldzki" location ("cars" or "big bridge") , an error occurs:
```
Uncaught Error: Objects are not valid as a React child (found: object with keys {displayValue, type, value}). If you meant to render a collection of children, use an array instead.
```

2024-12-16 16:39 UTC, x-Milosz commented on src/components/Map/components/NavigateMeButton.jsx
> +const NavigateMeButton = ({ onClick }) => {
Changed

2024-12-16 16:39 UTC, x-Milosz commented on src/components/Map/components/NavigateMeButton.jsx
> +                {t('navigateMe')}
Changed

2024-12-16 16:40 UTC, x-Milosz commented on src/components/Map/MapComponent.jsx
> +            {userPosition && <NavigateMeButton onClick={handleNavigateMeButtonClick} />}
Added toast with proper contrast

2024-12-16 16:40 UTC, x-Milosz commented on src/components/Map/components/NavigateMeButton.jsx
> +                id="navigateMeButton"
Changed

2024-12-16 16:40 UTC, x-Milosz commented on src/locales/en/map.json
> +    "navigateMe": "Navigate me",
Changed

2024-12-16 16:40 UTC, x-Milosz commented on src/locales/pl/map.json
> +    "navigateMe": "Nawiguj mnie",
Changed

2024-12-17 14:20 UTC, raven-wing commented on src/components/Map/MapComponent.jsx
> +                {window.ACCESSIBILITY_TABLE && (
Make it consistent with others
```suggestion
                {window.SHOW_ACCESSIBILITY_TABLE && (
```

2024-12-17 14:20 UTC, raven-wing commented on src/components/Map/components/ListView.jsx
> +                    backgroundColor: window.SECONDARY_COLOR,
created separated issue for #87

2024-12-17 14:20 UTC, raven-wing commented on src/locales/en/map.json
> +    "navigateMe": "Navigate me",
This doesn't showa as obsolete, so... it seems not?

2025-01-11 21:08 UTC, raven-wing approved these changes

2025-01-11 21:09 UTC, merged